/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CadastroEscolar;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuário
 */
public class Relatorios extends javax.swing.JDialog {

    /**
     * Creates new form Relatorios
     */
    
   private int tipo;
   private DataBase dataBase;
   
    public Relatorios(java.awt.Frame parent, boolean modal, DataBase dataBase, int tipo) {
        super(parent, modal);
        initComponents();
        this.tipo = tipo;
        this.dataBase = dataBase;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        relTabela = new javax.swing.JTable();
        relTitulo = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        relTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(relTabela);

        relTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(500, 500, 500)
                        .addComponent(voltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(relTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(relTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(voltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        DefaultTableModel tabela;
        String[][] informacoes;
        if(tipo == 0){
            ArrayList<Professor> dados = dataBase.getProfessores();
            relTitulo.setText("Relatório de Professores");
            String[] nomearColunas = {"Nome","Cpf","Idade","Login","Senha","Disciplinas Ministradas"};
            informacoes = new String[dados.size()][6];
            for(int i = 0; i < dados.size(); i++){
                informacoes[i][0] = dados.get(i).getNome();
                informacoes[i][1] = dados.get(i).getCpf();
                informacoes[i][2] = String.valueOf(dados.get(i).getIdade());
                informacoes[i][3] = dados.get(i).getLogin();
                informacoes[i][4] = dados.get(i).getSenha();
                informacoes[i][5] = dados.get(i).getDisciplinasMinistradas();
            }
            tabela = new DefaultTableModel(informacoes, nomearColunas);
            this.relTabela.setModel(tabela);
        }else if (tipo == 1){
            ArrayList<Estudante> dados = dataBase.getEstudantes();
            relTitulo.setText("Relatório de Estudantes");
            String[] nomearColunas = {"Nome","Cpf","Idade","Login","Senha","Disciplinas Cursadas"};
            informacoes = new String[dados.size()][6];
            for(int i = 0; i < dados.size(); i++){
                informacoes[i][0] = dados.get(i).getNome();
                informacoes[i][1] = dados.get(i).getCpf();
                informacoes[i][2] = String.valueOf(dados.get(i).getIdade());
                informacoes[i][3] = dados.get(i).getLogin();
                informacoes[i][4] = dados.get(i).getSenha();
                informacoes[i][5] = dados.get(i).getDisciplinasCursadas();
            } 
            tabela = new DefaultTableModel(informacoes, nomearColunas);
            this.relTabela.setModel(tabela);
        } 
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable relTabela;
    private javax.swing.JLabel relTitulo;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
